---
title: "CURRICULUM VITAE"
description: |

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# WORK EXPERIENCE

| Timeframe             | Event                                                                                           |
|-----------------------|-------------------------------------------------------------------------------------------------|
| since 2024            | Research Support and Research Data Management, University of Applied Sciences and Arts Northwestern Switzerland (FHNW) |
| 2020 - 2024           | Assistant and PhD Candidate, HCI Research Group, University of Basel                            |
| 2019 - 2020           | Student Research Assistant, HCI Research Group, University of Basel                             |
| 2018 - 2020           | Student Research Assistant for Data Analysis, Department on Medical Communication, University Hospital Basel      |
| Nov - Dec 2018        | UX Research Project Intern, HCI Research Group, University of Basel                             |
| Jun - Sep 2017        | Intern, Department for Psychosomatics, University Hospital Basel                                |
| Mar - Apr 2017        | UX Research Intern, HCI Research Group, University of Basel                                     |
| 2014 - 2015           | Intern, medical outpatient clinic and medical ward 5.1, University Hospital Basel               |


# EDUCATION

| Timeframe             | Event                                                                                           |
|-----------------------|-------------------------------------------------------------------------------------------------|
| 2020 - 2024           | PhD in Psychology, HCI Research Group, University of Basel                                      |
| 2018 - 2020           | Master of Science in Psychology, University of Basel                                            |
| 2015 - 2018           | Bachelor of Science in Psychology, University of Basel                                          |
| 2009 - 2014           | Bilingual Swiss Matura (German & English), International Baccalaureate                          |

# TEACHING

| Timeframe                                        | Event                                                                                                                                   |
|--------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------|
| 2024                                             | Supervision of Bachelor's and Master's Theses                                                                                           |
| Spring Semester 2024                             | Seminar, ["Current Research Topics in HCI"](https://vorlesungsverzeichnis.unibas.ch/en/investigation?id=284238)                         |
| 2023                                             | Supervision of Bachelor's and Master's Theses                                                                                           |
| Fall Semester 2023                               | Seminar, ["Central Concepts and Constructs of User Experience"](https://vorlesungsverzeichnis.unibas.ch/en/home?id=277698)              |
| Spring Semester 2023                             | Seminar, ["Current Research Topics in HCI"](https://vorlesungsverzeichnis.unibas.ch/en/investigation?id=272186)                         |
| Spring Semester 2023                             | Seminar, ["Online Research in HCI: Scale Construction and Analysis"](https://vorlesungsverzeichnis.unibas.ch/en/investigation?id=272184)|
| 2022                                             | Supervision of Bachelor's and Master's Theses                                                                                           |
| Fall Semester 2022                               | Seminar, ["Research Methods in HCI"](https://vorlesungsverzeichnis.unibas.ch/en/investigation?id=267355)                                |
| Spring Semester 2022                             | Seminar, ["Current Research Topics in HCI"](https://vorlesungsverzeichnis.unibas.ch/en/investigation?id=267444)                         |
| Spring Semester 2022                             | Seminar, ["Online Research in HCI: Scale Construction and Analysis"](https://vorlesungsverzeichnis.unibas.ch/en/investigation?id=263778)|
| 2021                                             | Supervision of Bachelor's and Master's Theses                                                                                           |
| Fall Semester 2021                               | Seminar, ["Research Methods in HCI"](https://vorlesungsverzeichnis.unibas.ch/en/investigation?id=259900)                                |
| Spring Semester 2021                             | Seminar, ["Current Research Topics in HCI"](https://vorlesungsverzeichnis.unibas.ch/en/investigation?id=255201)                         |
| Spring Semester 2021                             | Seminar, ["Online Research in HCI: Scale Construction and Analysis"](https://vorlesungsverzeichnis.unibas.ch/en/investigation?id=258364)|