---
title: "RESEARCH ACTIVITY"
description: |

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# PUBLICATIONS
    
## Journal Articles
 
### 2024

Brühlmann, F., Memeti, Z., Aeschbach, L. F., Perrig, S. A. C., & Opwis, K. (2024). The effectiveness of warning statements in reducing careless responding in crowdsourced online surveys. *Behavior research methods*, 1-14. https://doi.org/10.3758/s13428-023-02321-z

Perrig, S. A. C., Aeschbach, L. F., Scharowski, N., von Felten, N., Opwis, K., & Brühlmann, F. (2024). Measurement Practices in User Experience (UX) Research: A Systematic Quantitative Literature Review. *Front. Comput. Sci. Sec. Human-Media Interaction*, 6, 1-17. https://doi.org/10.3389/fcomp.2024.1368860

Perrig, S. A. C., von Felten, N., Vollenwyder, B., & Opwis, K. (in press). Development and Psychometric Validation of a Positively Worded German Version of the System Usability Scale (SUS). *International Journal of Human–Computer Interaction*. https://doi.org/10.1080/10447318.2024.2434720
 
### 2023
 
Perrig, S. A. C., Ueffing, D., Opwis, K., & Brühlmann, F. (2023). Smartphone App Aesthetics Influence Users' Experience and Performance. *Front. Psychol. Sec. Human-Media Interaction*, 14, 1-18. https://doi.org/10.3389/fpsyg.2023.1113842

Perrig, S. A. C., von Felten, N., Honda, M., Opwis, K., & Brühlmann, F. (2023). Development and Validation of a Positive-Item Version of the Visual Aesthetics of Websites Inventory: The VisAWI-Pos. *International Journal of Human–Computer Interaction*, *40*(20), 6622-6646. https://doi.org/10.1080/10447318.2023.2258634

Scharowski, N., Perrig, S. A. C., Svab, M., Opwis, K., & Brühlmann, F. (2023). Exploring the Effects of Human-Centered AI Explanations on Trust and Reliance. *Front. Comput. Sci. Sec. Theoretical Computer Science*, 5. https://doi.org/10.3389/fcomp.2023.1151150
    
### 2021
    
Aeschbach, L. F., Perrig, S. A. C., Weder, L., Opwis, K., & Brühlmann, F. (2021). Transparency in Measurement Reporting: A Systematic Literature Review of CHI PLAY. *Proc. ACM Hum.-Comput. Interact., 5(CHI PLAY)*. **Honorable Mentions**. https://doi.org/10.1145/3474660
    
Hochstrasser, S. R., Metzger, K., Vincent, A. M., Becker, C., Keller, A. K. J., Beck, K., Perrig, S., Tisljar, K., Sutter, R., Schuetz, P., Bernasconi, L., Neyer, P., Marsch, S., & Hunziker, S. (2021). Trimethylamine-N-oxide (TMAO) predicts short- and long-term mortality and poor neurological outcome in out-of-hospital cardiac arrest patients. *Clinical Chemistry and Laboratory Medicine (CCLM)*, *59*(2), 393–402. https://doi.org/10.1515/cclm-2020-0159  
    
### 2020
    
Beck, K., Vincent, A., Thommen, E., Widmer, M., Becker, C., Perrig, S., Keller, A., & Hunziker, S. (2020). Post Intensive Care Syndrome in out-of-hospital cardiac arrest patients: A prospective observational study. *Journal of Psychosomatic Research*, *133*, 110064. https://doi.org/10.1016/j.jpsychores.2020.110064
    
Becker, C., Künzli, N., Perrig, S., Beck, K., Vincent, A., Widmer, M., Thommen, E., Schaefert, R., Bassetti, S., & Hunziker, S. (2020). Code status discussions in medical inpatients: results of a survey of patients and physicians. *Swiss Medical Weekly*, *150*(1314). https://doi.org/10.4414/smw.2020.20194
    
Boerlin, A., Luescher, T., Becker, C., Perrig, S., Thommen, E., Widmer, M., Beck, K., Vincent, A., Tisljar, K., Bernasconi, L., & others. (2020). Low Plasma Sphingomyelin Levels Show a Weak Association with Poor Neurological Outcome in Cardiac Arrest Patients: Results from the Prospective, Observational COMMUNICATE Trial. *Journal of Clinical Medicine*, *9*(4), 897. https://doi.org/10.3390/jcm9040897
    
Herzog, N., Laager, R., Thommen, E., Widmer, M., Vincent, A. M., Keller, A., Becker, C., Beck, K., Perrig, S., Bernasconi, L., & others. (2020). Association of Taurine with In-Hospital Mortality in Patients after Out-of-Hospital Cardiac Arrest: Results from the Prospective, Observational COMMUNICATE Study. *Journal of Clinical Medicine*, *9*(5), 1405. https://doi.org/10.3390/jcm9051405
    
Widmer, M., Thommen, E. B., Becker, C., Beck, K., Vincent, A. M., Perrig, S., Keller, A., Bernasconi, L., Neyer, P., Marsch, S., & others. (2020). Association of acyl carnitines and mortality in out-of-hospital-cardiac-arrest patients: Results of a prospective observational study. *Journal of Critical Care*, *58*. https://doi.org/10.1016/j.jcrc.2020.03.009

## Conference Proceedings

### 2024

Perrig, S. A. C., Scharowski, N., Brühlmann, F., von Felten, N., Opwis, K., & Aeschbach, L. F. (2024). Independent validation of the Player Experience Inventory: Findings from a large set of video game players. *Proceedings of the CHI Conference on Human Factors in Computing Systems*. https://doi.org/10.1145/3613904.3642270 

### 2023

Perrig, S. A. C., Scharowski, N., & Brühlmann, F. (2023). Trust Issues with Trust Scales: Examining the Psychometric Quality of Trust Measures in the Context of AI. *CHI EA '23: Extended Abstracts of the 2023 CHI Conference on Human Factors in Computing Systems*, 1-7. https://doi.org/10.1145/3544549.3585808

Scharowski, N., & Perrig, S. A. C. (2023). Distrust in (X)AI--Measurement Artifact or Distinct Construct?. *CHI 2023 TRAIT Workshop on Trust and Reliance in AI-Human Teams*. https://doi.org/10.48550/arXiv.2303.16495
    
### 2022

Memeti, Z., Brühlmann, F., & Perrig, S. A. C. (2022). LoL, Why Do You Even Play? Validating the Motives for Online Gaming Questionnaire in the Context of League of Legends. *Extended Abstracts of the 2022 Annual Symposium on Computer-Human Interaction in Play*, 81-86. https://doi.org/10.1145/3505270.3558350

Scharowski, N., Perrig, S. A. C., von Felten, N., & Brühlmann, F. (2022). Trust and Reliance in XAI–Distinguishing Between Attitudinal and Behavioral Measures. *CHI 2022 TRAIT Workshop on Trust and Reliance in AI-Human Teams*. 
https://doi.org/10.48550/arXiv.2203.12318
    
von Felten, N., Brühlmann, F., & Perrig, S. A. C. (2022). Independent Validation of the Video Game Dispositional Flow Scale With League of Legends Players. *Extended Abstracts of the 2022 Annual Symposium on Computer-Human Interaction in Play*, 44-50. https://doi.org/10.1145/3505270.3558351   

### 2021
    
Kayser, D., Perrig, S. A. C., & Brühlmann, F. (2021). Measuring Players’ Experience of Need Satisfaction in Digital Games: An Analysis of the Factor Structure of the UPEQ. *Extended Abstracts of the 2021 Annual Symposium on Computer-Human Interaction in Play*, 158–162. https://doi.org/10.1145/3450337.3483499

## Additional Work

Perrig, S. A. C. (2024). Measuring and Understanding User Experience: Current State and Future Needs. *Doctoral Thesis*, University of Basel, Faculty of Psychology. https://doi.org/10.5451/unibas-ep96368

Scharowski, N., Perrig, S. A. C., Aeschbach, L. F., von Felten, N., Opwis, K., Wintersberger, P., & Brühlmann F. (2024). To Trust or Distrust Trust Measures: Validating Questionnaires for Trust in AI. *arXiv Preprint*. https://doi.org/10.48550/arXiv.2403.00582

Perrig, S. (2020). Validating the AttrakDiff: Structured literature review and questionnaire validation in a mobile device setting. *Master's Thesis*. 

Perrig, S. (2018). Measuring user experience: Overview and comparison oft two commonly used questionnaires. *Bachelor's Thesis*. https://doi.org/10.31237/osf.io/bkx5y

# AWARDS

CHI PLAY 2021 Honorable Mentions Award (top 5 %)
    
# TALKS
    
Perrig, S. (2021, December 1). Measuring UX - Current State and Future Opportunities. *UX Schweiz - Basel Meetups*. https://www.meetup.com/ux-basel-meetups/events/281969432/